version: 2.1

jobs:
  laravel-job:
    docker:
      # Specify the version you desire here
      - image: cimg/php:7.4.31-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      # 
      # - image: redis:3

    steps:
      - checkout

      # Download and cache dependencies
      - run: sudo composer self-update
      # composer cache
      - restore_cache:
          keys:
              - composer-v1-{{ checksum "composer.lock" }}
              - composer-v1-
      - run: mv .env.testing .env
      - run: composer install -n --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
              - vendor
      - restore_cache: # special step to restore the dependency cache if `package.json` does not change
          keys:
              - node-v1-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
              - node-v1-
      - run: npm install
      - save_cache: # special step to save the dependency cache with the `package.json` cache key template
          key: node-v1-{{ checksum "package.json" }}
          paths:
              - node_modules
      - run: npm run production

      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true
      - run: vendor/bin/phpunit

workflows:
  my-workflow:
    jobs:
      - laravel-job